# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
variables:
  - name: GITHUB_TOKEN
    value: <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>

jobs:
- job: build
  displayName: Build job
  # Define the steps for the build job here
  # ...
  steps:
    - script: echo Hello, world!

- job: create_tag
  displayName: Create Git tag
  dependsOn: build
  condition: succeeded()
  steps:
  - script: |
      git config --global user.email "ahammadsayed577@gmail.com"
      git config --global user.name "sayed-hub"
      echo ${{ variables.GITHUB_TOKEN }} | git credential-store --file ~/.git-credentials store
      git tag -a $(Build.BuildNumber) -m "Build passed for $(Build.SourceBranchName)"
      git push --tags
    displayName: Create and push Git tag
